// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: infrastructure/finish-line.proto

package pb_infrastructure

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinishLineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Time of event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishLineEvent) Reset() {
	*x = FinishLineEvent{}
	mi := &file_infrastructure_finish_line_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLineEvent) ProtoMessage() {}

func (x *FinishLineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_finish_line_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLineEvent.ProtoReflect.Descriptor instead.
func (*FinishLineEvent) Descriptor() ([]byte, []int) {
	return file_infrastructure_finish_line_proto_rawDescGZIP(), []int{0}
}

func (x *FinishLineEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_infrastructure_finish_line_proto protoreflect.FileDescriptor

const file_infrastructure_finish_line_proto_rawDesc = "" +
	"\n" +
	" infrastructure/finish-line.proto\x12\rprotobuf_msgs\"/\n" +
	"\x0fFinishLineEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestampB\x17Z\x15ase/pb_infrastructureb\x06proto3"

var (
	file_infrastructure_finish_line_proto_rawDescOnce sync.Once
	file_infrastructure_finish_line_proto_rawDescData []byte
)

func file_infrastructure_finish_line_proto_rawDescGZIP() []byte {
	file_infrastructure_finish_line_proto_rawDescOnce.Do(func() {
		file_infrastructure_finish_line_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infrastructure_finish_line_proto_rawDesc), len(file_infrastructure_finish_line_proto_rawDesc)))
	})
	return file_infrastructure_finish_line_proto_rawDescData
}

var file_infrastructure_finish_line_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_infrastructure_finish_line_proto_goTypes = []any{
	(*FinishLineEvent)(nil), // 0: protobuf_msgs.FinishLineEvent
}
var file_infrastructure_finish_line_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infrastructure_finish_line_proto_init() }
func file_infrastructure_finish_line_proto_init() {
	if File_infrastructure_finish_line_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrastructure_finish_line_proto_rawDesc), len(file_infrastructure_finish_line_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infrastructure_finish_line_proto_goTypes,
		DependencyIndexes: file_infrastructure_finish_line_proto_depIdxs,
		MessageInfos:      file_infrastructure_finish_line_proto_msgTypes,
	}.Build()
	File_infrastructure_finish_line_proto = out.File
	file_infrastructure_finish_line_proto_goTypes = nil
	file_infrastructure_finish_line_proto_depIdxs = nil
}
