// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: simulator/simulator.proto

package pb_simulator_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible Sim Requests. Useful for interfaces with Gym
type SimStatus int32

const (
	SimStatus_SIM_PAUSED    SimStatus = 0 // Simulator is paused
	SimStatus_SIM_REQ_STEP  SimStatus = 1 // Request single step
	SimStatus_SIM_REQ_RESET SimStatus = 2 // Request hard reset
)

// Enum value maps for SimStatus.
var (
	SimStatus_name = map[int32]string{
		0: "SIM_PAUSED",
		1: "SIM_REQ_STEP",
		2: "SIM_REQ_RESET",
	}
	SimStatus_value = map[string]int32{
		"SIM_PAUSED":    0,
		"SIM_REQ_STEP":  1,
		"SIM_REQ_RESET": 2,
	}
)

func (x SimStatus) Enum() *SimStatus {
	p := new(SimStatus)
	*p = x
	return p
}

func (x SimStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_simulator_simulator_proto_enumTypes[0].Descriptor()
}

func (SimStatus) Type() protoreflect.EnumType {
	return &file_simulator_simulator_proto_enumTypes[0]
}

func (x SimStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimStatus.Descriptor instead.
func (SimStatus) EnumDescriptor() ([]byte, []int) {
	return file_simulator_simulator_proto_rawDescGZIP(), []int{0}
}

// Simulator sensor outputs.
type SimulatorImageOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Pixels        []byte                 `protobuf:"bytes,4,opt,name=pixels,proto3" json:"pixels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulatorImageOutput) Reset() {
	*x = SimulatorImageOutput{}
	mi := &file_simulator_simulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatorImageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatorImageOutput) ProtoMessage() {}

func (x *SimulatorImageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_simulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatorImageOutput.ProtoReflect.Descriptor instead.
func (*SimulatorImageOutput) Descriptor() ([]byte, []int) {
	return file_simulator_simulator_proto_rawDescGZIP(), []int{0}
}

func (x *SimulatorImageOutput) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SimulatorImageOutput) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SimulatorImageOutput) GetPixels() []byte {
	if x != nil {
		return x.Pixels
	}
	return nil
}

// Generic state of Simulator
type SimulatorState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         float32                `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`                                              // Meters per second
	WheelOffTrack []bool                 `protobuf:"varint,2,rep,packed,name=wheel_off_track,json=wheelOffTrack,proto3" json:"wheel_off_track,omitempty"` // [0] = FL, [1] = FR, [2] = RL, [3] = RR
	Image         *SimulatorImageOutput  `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`                                                // Image frame
	Pos           []float32              `protobuf:"fixed32,4,rep,packed,name=pos,proto3" json:"pos,omitempty"`                                           // [0] = x, [1] = y, [2] = z
	IsDrifting    bool                   `protobuf:"varint,5,opt,name=isDrifting,proto3" json:"isDrifting,omitempty"`                                     // =false when not drifting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulatorState) Reset() {
	*x = SimulatorState{}
	mi := &file_simulator_simulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulatorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulatorState) ProtoMessage() {}

func (x *SimulatorState) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_simulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulatorState.ProtoReflect.Descriptor instead.
func (*SimulatorState) Descriptor() ([]byte, []int) {
	return file_simulator_simulator_proto_rawDescGZIP(), []int{1}
}

func (x *SimulatorState) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SimulatorState) GetWheelOffTrack() []bool {
	if x != nil {
		return x.WheelOffTrack
	}
	return nil
}

func (x *SimulatorState) GetImage() *SimulatorImageOutput {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *SimulatorState) GetPos() []float32 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SimulatorState) GetIsDrifting() bool {
	if x != nil {
		return x.IsDrifting
	}
	return false
}

var File_simulator_simulator_proto protoreflect.FileDescriptor

const file_simulator_simulator_proto_rawDesc = "" +
	"\n" +
	"\x19simulator/simulator.proto\x12\rprotobuf_msgs\"\\\n" +
	"\x14SimulatorImageOutput\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x16\n" +
	"\x06pixels\x18\x04 \x01(\fR\x06pixels\"\xbb\x01\n" +
	"\x0eSimulatorState\x12\x14\n" +
	"\x05speed\x18\x01 \x01(\x02R\x05speed\x12&\n" +
	"\x0fwheel_off_track\x18\x02 \x03(\bR\rwheelOffTrack\x129\n" +
	"\x05image\x18\x03 \x01(\v2#.protobuf_msgs.SimulatorImageOutputR\x05image\x12\x10\n" +
	"\x03pos\x18\x04 \x03(\x02R\x03pos\x12\x1e\n" +
	"\n" +
	"isDrifting\x18\x05 \x01(\bR\n" +
	"isDrifting*@\n" +
	"\tSimStatus\x12\x0e\n" +
	"\n" +
	"SIM_PAUSED\x10\x00\x12\x10\n" +
	"\fSIM_REQ_STEP\x10\x01\x12\x11\n" +
	"\rSIM_REQ_RESET\x10\x02B\x1bZ\x19ase/pb_simulator_messagesb\x06proto3"

var (
	file_simulator_simulator_proto_rawDescOnce sync.Once
	file_simulator_simulator_proto_rawDescData []byte
)

func file_simulator_simulator_proto_rawDescGZIP() []byte {
	file_simulator_simulator_proto_rawDescOnce.Do(func() {
		file_simulator_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulator_simulator_proto_rawDesc), len(file_simulator_simulator_proto_rawDesc)))
	})
	return file_simulator_simulator_proto_rawDescData
}

var file_simulator_simulator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_simulator_simulator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_simulator_simulator_proto_goTypes = []any{
	(SimStatus)(0),               // 0: protobuf_msgs.SimStatus
	(*SimulatorImageOutput)(nil), // 1: protobuf_msgs.SimulatorImageOutput
	(*SimulatorState)(nil),       // 2: protobuf_msgs.SimulatorState
}
var file_simulator_simulator_proto_depIdxs = []int32{
	1, // 0: protobuf_msgs.SimulatorState.image:type_name -> protobuf_msgs.SimulatorImageOutput
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_simulator_simulator_proto_init() }
func file_simulator_simulator_proto_init() {
	if File_simulator_simulator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulator_simulator_proto_rawDesc), len(file_simulator_simulator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simulator_simulator_proto_goTypes,
		DependencyIndexes: file_simulator_simulator_proto_depIdxs,
		EnumInfos:         file_simulator_simulator_proto_enumTypes,
		MessageInfos:      file_simulator_simulator_proto_msgTypes,
	}.Build()
	File_simulator_simulator_proto = out.File
	file_simulator_simulator_proto_goTypes = nil
	file_simulator_simulator_proto_depIdxs = nil
}
