// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: outputs/controller.proto

package pb_outputs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControllerOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Steering angle (-1.0 to 1.0 <-> left - right)
	SteeringAngle float32 `protobuf:"fixed32,2,opt,name=steeringAngle,proto3" json:"steeringAngle,omitempty"`
	// Throttle (-1.0 to 1.0 <-> full reverse - full forward)
	LeftThrottle  float32 `protobuf:"fixed32,3,opt,name=leftThrottle,proto3" json:"leftThrottle,omitempty"`
	RightThrottle float32 `protobuf:"fixed32,4,opt,name=rightThrottle,proto3" json:"rightThrottle,omitempty"`
	// Onboard lights (0.0 to 1.0 <-> off - on)
	FrontLights bool `protobuf:"varint,5,opt,name=frontLights,proto3" json:"frontLights,omitempty"`
	// Fan speed (0.0 to 1.0 <-> off - full speed)
	FanSpeed float32 `protobuf:"fixed32,6,opt,name=fanSpeed,proto3" json:"fanSpeed,omitempty"`
	// Useful for debugging
	RawError      float32 `protobuf:"fixed32,7,opt,name=rawError,proto3" json:"rawError,omitempty"`       // the error value before quadratic scaling
	ScaledError   float32 `protobuf:"fixed32,8,opt,name=scaledError,proto3" json:"scaledError,omitempty"` // the error value after quadratic scaling, but before PID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerOutput) Reset() {
	*x = ControllerOutput{}
	mi := &file_outputs_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerOutput) ProtoMessage() {}

func (x *ControllerOutput) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerOutput.ProtoReflect.Descriptor instead.
func (*ControllerOutput) Descriptor() ([]byte, []int) {
	return file_outputs_controller_proto_rawDescGZIP(), []int{0}
}

func (x *ControllerOutput) GetSteeringAngle() float32 {
	if x != nil {
		return x.SteeringAngle
	}
	return 0
}

func (x *ControllerOutput) GetLeftThrottle() float32 {
	if x != nil {
		return x.LeftThrottle
	}
	return 0
}

func (x *ControllerOutput) GetRightThrottle() float32 {
	if x != nil {
		return x.RightThrottle
	}
	return 0
}

func (x *ControllerOutput) GetFrontLights() bool {
	if x != nil {
		return x.FrontLights
	}
	return false
}

func (x *ControllerOutput) GetFanSpeed() float32 {
	if x != nil {
		return x.FanSpeed
	}
	return 0
}

func (x *ControllerOutput) GetRawError() float32 {
	if x != nil {
		return x.RawError
	}
	return 0
}

func (x *ControllerOutput) GetScaledError() float32 {
	if x != nil {
		return x.ScaledError
	}
	return 0
}

var File_outputs_controller_proto protoreflect.FileDescriptor

const file_outputs_controller_proto_rawDesc = "" +
	"\n" +
	"\x18outputs/controller.proto\x12\rprotobuf_msgs\"\xfe\x01\n" +
	"\x10ControllerOutput\x12$\n" +
	"\rsteeringAngle\x18\x02 \x01(\x02R\rsteeringAngle\x12\"\n" +
	"\fleftThrottle\x18\x03 \x01(\x02R\fleftThrottle\x12$\n" +
	"\rrightThrottle\x18\x04 \x01(\x02R\rrightThrottle\x12 \n" +
	"\vfrontLights\x18\x05 \x01(\bR\vfrontLights\x12\x1a\n" +
	"\bfanSpeed\x18\x06 \x01(\x02R\bfanSpeed\x12\x1a\n" +
	"\brawError\x18\a \x01(\x02R\brawError\x12 \n" +
	"\vscaledError\x18\b \x01(\x02R\vscaledErrorB\x10Z\x0ease/pb_outputsb\x06proto3"

var (
	file_outputs_controller_proto_rawDescOnce sync.Once
	file_outputs_controller_proto_rawDescData []byte
)

func file_outputs_controller_proto_rawDescGZIP() []byte {
	file_outputs_controller_proto_rawDescOnce.Do(func() {
		file_outputs_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outputs_controller_proto_rawDesc), len(file_outputs_controller_proto_rawDesc)))
	})
	return file_outputs_controller_proto_rawDescData
}

var file_outputs_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_outputs_controller_proto_goTypes = []any{
	(*ControllerOutput)(nil), // 0: protobuf_msgs.ControllerOutput
}
var file_outputs_controller_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outputs_controller_proto_init() }
func file_outputs_controller_proto_init() {
	if File_outputs_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outputs_controller_proto_rawDesc), len(file_outputs_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outputs_controller_proto_goTypes,
		DependencyIndexes: file_outputs_controller_proto_depIdxs,
		MessageInfos:      file_outputs_controller_proto_msgTypes,
	}.Build()
	File_outputs_controller_proto = out.File
	file_outputs_controller_proto_goTypes = nil
	file_outputs_controller_proto_depIdxs = nil
}
