// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: outputs/generic.proto

package pb_outputs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This message holds a single integer value, it will be plotted in the debug view of roverctl
type GenericIntScalar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericIntScalar) Reset() {
	*x = GenericIntScalar{}
	mi := &file_outputs_generic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericIntScalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericIntScalar) ProtoMessage() {}

func (x *GenericIntScalar) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_generic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericIntScalar.ProtoReflect.Descriptor instead.
func (*GenericIntScalar) Descriptor() ([]byte, []int) {
	return file_outputs_generic_proto_rawDescGZIP(), []int{0}
}

func (x *GenericIntScalar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericIntScalar) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// This message holds a single float value, it will be plotted in the debug view of roverctl
type GenericFloatScalar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericFloatScalar) Reset() {
	*x = GenericFloatScalar{}
	mi := &file_outputs_generic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericFloatScalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericFloatScalar) ProtoMessage() {}

func (x *GenericFloatScalar) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_generic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericFloatScalar.ProtoReflect.Descriptor instead.
func (*GenericFloatScalar) Descriptor() ([]byte, []int) {
	return file_outputs_generic_proto_rawDescGZIP(), []int{1}
}

func (x *GenericFloatScalar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericFloatScalar) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// This message holds a single boolean value, it will *NOT* be plotted in the debug view of roverctl
type GenericBoolScalar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericBoolScalar) Reset() {
	*x = GenericBoolScalar{}
	mi := &file_outputs_generic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericBoolScalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericBoolScalar) ProtoMessage() {}

func (x *GenericBoolScalar) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_generic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericBoolScalar.ProtoReflect.Descriptor instead.
func (*GenericBoolScalar) Descriptor() ([]byte, []int) {
	return file_outputs_generic_proto_rawDescGZIP(), []int{2}
}

func (x *GenericBoolScalar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericBoolScalar) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

// This message holds a single string value, it will *NOT* be plotted in the debug view of roverctl
type GenericStringScalar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericStringScalar) Reset() {
	*x = GenericStringScalar{}
	mi := &file_outputs_generic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericStringScalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericStringScalar) ProtoMessage() {}

func (x *GenericStringScalar) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_generic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericStringScalar.ProtoReflect.Descriptor instead.
func (*GenericStringScalar) Descriptor() ([]byte, []int) {
	return file_outputs_generic_proto_rawDescGZIP(), []int{3}
}

func (x *GenericStringScalar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericStringScalar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// This message holds an array of integer values, it will *NOT* be plotted in the debug view of roverctl
type GenericIntArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []int32                `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericIntArray) Reset() {
	*x = GenericIntArray{}
	mi := &file_outputs_generic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericIntArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericIntArray) ProtoMessage() {}

func (x *GenericIntArray) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_generic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericIntArray.ProtoReflect.Descriptor instead.
func (*GenericIntArray) Descriptor() ([]byte, []int) {
	return file_outputs_generic_proto_rawDescGZIP(), []int{4}
}

func (x *GenericIntArray) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericIntArray) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// This message holds an array of float values, it will *NOT* be plotted in the debug view of roverctl
type GenericFloatArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericFloatArray) Reset() {
	*x = GenericFloatArray{}
	mi := &file_outputs_generic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericFloatArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericFloatArray) ProtoMessage() {}

func (x *GenericFloatArray) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_generic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericFloatArray.ProtoReflect.Descriptor instead.
func (*GenericFloatArray) Descriptor() ([]byte, []int) {
	return file_outputs_generic_proto_rawDescGZIP(), []int{5}
}

func (x *GenericFloatArray) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericFloatArray) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// This message holds an array of boolean values, it will *NOT* be plotted in the debug view of roverctl
type GenericBoolArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []bool                 `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericBoolArray) Reset() {
	*x = GenericBoolArray{}
	mi := &file_outputs_generic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericBoolArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericBoolArray) ProtoMessage() {}

func (x *GenericBoolArray) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_generic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericBoolArray.ProtoReflect.Descriptor instead.
func (*GenericBoolArray) Descriptor() ([]byte, []int) {
	return file_outputs_generic_proto_rawDescGZIP(), []int{6}
}

func (x *GenericBoolArray) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericBoolArray) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

// This message holds an array of string values, it will *NOT* be plotted in the debug view of roverctl
type GenericStringArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericStringArray) Reset() {
	*x = GenericStringArray{}
	mi := &file_outputs_generic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericStringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericStringArray) ProtoMessage() {}

func (x *GenericStringArray) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_generic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericStringArray.ProtoReflect.Descriptor instead.
func (*GenericStringArray) Descriptor() ([]byte, []int) {
	return file_outputs_generic_proto_rawDescGZIP(), []int{7}
}

func (x *GenericStringArray) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericStringArray) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_outputs_generic_proto protoreflect.FileDescriptor

const file_outputs_generic_proto_rawDesc = "" +
	"\n" +
	"\x15outputs/generic.proto\x12\rprotobuf_msgs\":\n" +
	"\x10GenericIntScalar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"<\n" +
	"\x12GenericFloatScalar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\";\n" +
	"\x11GenericBoolScalar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"=\n" +
	"\x13GenericStringScalar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\";\n" +
	"\x0fGenericIntArray\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x05R\x06values\"=\n" +
	"\x11GenericFloatArray\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\"<\n" +
	"\x10GenericBoolArray\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\bR\x06values\">\n" +
	"\x12GenericStringArray\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06valuesB\x10Z\x0ease/pb_outputsb\x06proto3"

var (
	file_outputs_generic_proto_rawDescOnce sync.Once
	file_outputs_generic_proto_rawDescData []byte
)

func file_outputs_generic_proto_rawDescGZIP() []byte {
	file_outputs_generic_proto_rawDescOnce.Do(func() {
		file_outputs_generic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outputs_generic_proto_rawDesc), len(file_outputs_generic_proto_rawDesc)))
	})
	return file_outputs_generic_proto_rawDescData
}

var file_outputs_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_outputs_generic_proto_goTypes = []any{
	(*GenericIntScalar)(nil),    // 0: protobuf_msgs.GenericIntScalar
	(*GenericFloatScalar)(nil),  // 1: protobuf_msgs.GenericFloatScalar
	(*GenericBoolScalar)(nil),   // 2: protobuf_msgs.GenericBoolScalar
	(*GenericStringScalar)(nil), // 3: protobuf_msgs.GenericStringScalar
	(*GenericIntArray)(nil),     // 4: protobuf_msgs.GenericIntArray
	(*GenericFloatArray)(nil),   // 5: protobuf_msgs.GenericFloatArray
	(*GenericBoolArray)(nil),    // 6: protobuf_msgs.GenericBoolArray
	(*GenericStringArray)(nil),  // 7: protobuf_msgs.GenericStringArray
}
var file_outputs_generic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outputs_generic_proto_init() }
func file_outputs_generic_proto_init() {
	if File_outputs_generic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outputs_generic_proto_rawDesc), len(file_outputs_generic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outputs_generic_proto_goTypes,
		DependencyIndexes: file_outputs_generic_proto_depIdxs,
		MessageInfos:      file_outputs_generic_proto_msgTypes,
	}.Build()
	File_outputs_generic_proto = out.File
	file_outputs_generic_proto_goTypes = nil
	file_outputs_generic_proto_depIdxs = nil
}
