// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: outputs/imu.proto

package pb_outputs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImuSensorOutput struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Temperature         int32                   `protobuf:"varint,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Magnetometer        *ImuSensorOutput_Vector `protobuf:"bytes,2,opt,name=magnetometer,proto3" json:"magnetometer,omitempty"`
	Gyroscope           *ImuSensorOutput_Vector `protobuf:"bytes,3,opt,name=gyroscope,proto3" json:"gyroscope,omitempty"`
	Euler               *ImuSensorOutput_Vector `protobuf:"bytes,4,opt,name=euler,proto3" json:"euler,omitempty"`
	Accelerometer       *ImuSensorOutput_Vector `protobuf:"bytes,5,opt,name=accelerometer,proto3" json:"accelerometer,omitempty"`
	LinearAccelerometer *ImuSensorOutput_Vector `protobuf:"bytes,6,opt,name=linearAccelerometer,proto3" json:"linearAccelerometer,omitempty"`
	Velocity            *ImuSensorOutput_Vector `protobuf:"bytes,7,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Speed               float32                 `protobuf:"fixed32,8,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ImuSensorOutput) Reset() {
	*x = ImuSensorOutput{}
	mi := &file_outputs_imu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImuSensorOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImuSensorOutput) ProtoMessage() {}

func (x *ImuSensorOutput) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_imu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImuSensorOutput.ProtoReflect.Descriptor instead.
func (*ImuSensorOutput) Descriptor() ([]byte, []int) {
	return file_outputs_imu_proto_rawDescGZIP(), []int{0}
}

func (x *ImuSensorOutput) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ImuSensorOutput) GetMagnetometer() *ImuSensorOutput_Vector {
	if x != nil {
		return x.Magnetometer
	}
	return nil
}

func (x *ImuSensorOutput) GetGyroscope() *ImuSensorOutput_Vector {
	if x != nil {
		return x.Gyroscope
	}
	return nil
}

func (x *ImuSensorOutput) GetEuler() *ImuSensorOutput_Vector {
	if x != nil {
		return x.Euler
	}
	return nil
}

func (x *ImuSensorOutput) GetAccelerometer() *ImuSensorOutput_Vector {
	if x != nil {
		return x.Accelerometer
	}
	return nil
}

func (x *ImuSensorOutput) GetLinearAccelerometer() *ImuSensorOutput_Vector {
	if x != nil {
		return x.LinearAccelerometer
	}
	return nil
}

func (x *ImuSensorOutput) GetVelocity() *ImuSensorOutput_Vector {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *ImuSensorOutput) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type ImuSensorOutput_Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImuSensorOutput_Vector) Reset() {
	*x = ImuSensorOutput_Vector{}
	mi := &file_outputs_imu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImuSensorOutput_Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImuSensorOutput_Vector) ProtoMessage() {}

func (x *ImuSensorOutput_Vector) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_imu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImuSensorOutput_Vector.ProtoReflect.Descriptor instead.
func (*ImuSensorOutput_Vector) Descriptor() ([]byte, []int) {
	return file_outputs_imu_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ImuSensorOutput_Vector) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ImuSensorOutput_Vector) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ImuSensorOutput_Vector) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_outputs_imu_proto protoreflect.FileDescriptor

const file_outputs_imu_proto_rawDesc = "" +
	"\n" +
	"\x11outputs/imu.proto\x12\rprotobuf_msgs\"\xb3\x04\n" +
	"\x0fImuSensorOutput\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x05R\vtemperature\x12I\n" +
	"\fmagnetometer\x18\x02 \x01(\v2%.protobuf_msgs.ImuSensorOutput.VectorR\fmagnetometer\x12C\n" +
	"\tgyroscope\x18\x03 \x01(\v2%.protobuf_msgs.ImuSensorOutput.VectorR\tgyroscope\x12;\n" +
	"\x05euler\x18\x04 \x01(\v2%.protobuf_msgs.ImuSensorOutput.VectorR\x05euler\x12K\n" +
	"\raccelerometer\x18\x05 \x01(\v2%.protobuf_msgs.ImuSensorOutput.VectorR\raccelerometer\x12W\n" +
	"\x13linearAccelerometer\x18\x06 \x01(\v2%.protobuf_msgs.ImuSensorOutput.VectorR\x13linearAccelerometer\x12A\n" +
	"\bvelocity\x18\a \x01(\v2%.protobuf_msgs.ImuSensorOutput.VectorR\bvelocity\x12\x14\n" +
	"\x05speed\x18\b \x01(\x02R\x05speed\x1a2\n" +
	"\x06Vector\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01zB\x10Z\x0ease/pb_outputsb\x06proto3"

var (
	file_outputs_imu_proto_rawDescOnce sync.Once
	file_outputs_imu_proto_rawDescData []byte
)

func file_outputs_imu_proto_rawDescGZIP() []byte {
	file_outputs_imu_proto_rawDescOnce.Do(func() {
		file_outputs_imu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outputs_imu_proto_rawDesc), len(file_outputs_imu_proto_rawDesc)))
	})
	return file_outputs_imu_proto_rawDescData
}

var file_outputs_imu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_outputs_imu_proto_goTypes = []any{
	(*ImuSensorOutput)(nil),        // 0: protobuf_msgs.ImuSensorOutput
	(*ImuSensorOutput_Vector)(nil), // 1: protobuf_msgs.ImuSensorOutput.Vector
}
var file_outputs_imu_proto_depIdxs = []int32{
	1, // 0: protobuf_msgs.ImuSensorOutput.magnetometer:type_name -> protobuf_msgs.ImuSensorOutput.Vector
	1, // 1: protobuf_msgs.ImuSensorOutput.gyroscope:type_name -> protobuf_msgs.ImuSensorOutput.Vector
	1, // 2: protobuf_msgs.ImuSensorOutput.euler:type_name -> protobuf_msgs.ImuSensorOutput.Vector
	1, // 3: protobuf_msgs.ImuSensorOutput.accelerometer:type_name -> protobuf_msgs.ImuSensorOutput.Vector
	1, // 4: protobuf_msgs.ImuSensorOutput.linearAccelerometer:type_name -> protobuf_msgs.ImuSensorOutput.Vector
	1, // 5: protobuf_msgs.ImuSensorOutput.velocity:type_name -> protobuf_msgs.ImuSensorOutput.Vector
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_outputs_imu_proto_init() }
func file_outputs_imu_proto_init() {
	if File_outputs_imu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outputs_imu_proto_rawDesc), len(file_outputs_imu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outputs_imu_proto_goTypes,
		DependencyIndexes: file_outputs_imu_proto_depIdxs,
		MessageInfos:      file_outputs_imu_proto_msgTypes,
	}.Build()
	File_outputs_imu_proto = out.File
	file_outputs_imu_proto_goTypes = nil
	file_outputs_imu_proto_depIdxs = nil
}
