// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: outputs/laptime.proto

package pb_outputs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LapTimeOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LapTime       uint64                 `protobuf:"varint,1,opt,name=lapTime,proto3" json:"lapTime,omitempty"`           // Time of complete lap in ms
	LapStartTime  uint64                 `protobuf:"varint,2,opt,name=lapStartTime,proto3" json:"lapStartTime,omitempty"` // Start of the lap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LapTimeOutput) Reset() {
	*x = LapTimeOutput{}
	mi := &file_outputs_laptime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LapTimeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LapTimeOutput) ProtoMessage() {}

func (x *LapTimeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_laptime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LapTimeOutput.ProtoReflect.Descriptor instead.
func (*LapTimeOutput) Descriptor() ([]byte, []int) {
	return file_outputs_laptime_proto_rawDescGZIP(), []int{0}
}

func (x *LapTimeOutput) GetLapTime() uint64 {
	if x != nil {
		return x.LapTime
	}
	return 0
}

func (x *LapTimeOutput) GetLapStartTime() uint64 {
	if x != nil {
		return x.LapStartTime
	}
	return 0
}

var File_outputs_laptime_proto protoreflect.FileDescriptor

const file_outputs_laptime_proto_rawDesc = "" +
	"\n" +
	"\x15outputs/laptime.proto\x12\rprotobuf_msgs\"M\n" +
	"\rLapTimeOutput\x12\x18\n" +
	"\alapTime\x18\x01 \x01(\x04R\alapTime\x12\"\n" +
	"\flapStartTime\x18\x02 \x01(\x04R\flapStartTimeB\x10Z\x0ease/pb_outputsb\x06proto3"

var (
	file_outputs_laptime_proto_rawDescOnce sync.Once
	file_outputs_laptime_proto_rawDescData []byte
)

func file_outputs_laptime_proto_rawDescGZIP() []byte {
	file_outputs_laptime_proto_rawDescOnce.Do(func() {
		file_outputs_laptime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outputs_laptime_proto_rawDesc), len(file_outputs_laptime_proto_rawDesc)))
	})
	return file_outputs_laptime_proto_rawDescData
}

var file_outputs_laptime_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_outputs_laptime_proto_goTypes = []any{
	(*LapTimeOutput)(nil), // 0: protobuf_msgs.LapTimeOutput
}
var file_outputs_laptime_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outputs_laptime_proto_init() }
func file_outputs_laptime_proto_init() {
	if File_outputs_laptime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outputs_laptime_proto_rawDesc), len(file_outputs_laptime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outputs_laptime_proto_goTypes,
		DependencyIndexes: file_outputs_laptime_proto_depIdxs,
		MessageInfos:      file_outputs_laptime_proto_msgTypes,
	}.Build()
	File_outputs_laptime_proto = out.File
	file_outputs_laptime_proto_goTypes = nil
	file_outputs_laptime_proto_depIdxs = nil
}
