// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: outputs/rpm.proto

package pb_outputs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpmSensorOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeftRpm    float32 `protobuf:"fixed32,1,opt,name=leftRpm,proto3" json:"leftRpm,omitempty"`
	LeftAngle  float32 `protobuf:"fixed32,2,opt,name=leftAngle,proto3" json:"leftAngle,omitempty"`
	RightRpm   float32 `protobuf:"fixed32,3,opt,name=rightRpm,proto3" json:"rightRpm,omitempty"`
	RightAngle float32 `protobuf:"fixed32,4,opt,name=rightAngle,proto3" json:"rightAngle,omitempty"`
}

func (x *RpmSensorOutput) Reset() {
	*x = RpmSensorOutput{}
	mi := &file_outputs_rpm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpmSensorOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpmSensorOutput) ProtoMessage() {}

func (x *RpmSensorOutput) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_rpm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpmSensorOutput.ProtoReflect.Descriptor instead.
func (*RpmSensorOutput) Descriptor() ([]byte, []int) {
	return file_outputs_rpm_proto_rawDescGZIP(), []int{0}
}

func (x *RpmSensorOutput) GetLeftRpm() float32 {
	if x != nil {
		return x.LeftRpm
	}
	return 0
}

func (x *RpmSensorOutput) GetLeftAngle() float32 {
	if x != nil {
		return x.LeftAngle
	}
	return 0
}

func (x *RpmSensorOutput) GetRightRpm() float32 {
	if x != nil {
		return x.RightRpm
	}
	return 0
}

func (x *RpmSensorOutput) GetRightAngle() float32 {
	if x != nil {
		return x.RightAngle
	}
	return 0
}

var File_outputs_rpm_proto protoreflect.FileDescriptor

var file_outputs_rpm_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x2f, 0x72, 0x70, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x0f, 0x52, 0x70, 0x6d, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x66, 0x74, 0x52, 0x70,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6c, 0x65, 0x66, 0x74, 0x52, 0x70, 0x6d,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x69, 0x67, 0x68, 0x74, 0x52, 0x70, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x08, 0x72, 0x69, 0x67, 0x68, 0x74, 0x52, 0x70, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x61, 0x73,
	0x65, 0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_outputs_rpm_proto_rawDescOnce sync.Once
	file_outputs_rpm_proto_rawDescData = file_outputs_rpm_proto_rawDesc
)

func file_outputs_rpm_proto_rawDescGZIP() []byte {
	file_outputs_rpm_proto_rawDescOnce.Do(func() {
		file_outputs_rpm_proto_rawDescData = protoimpl.X.CompressGZIP(file_outputs_rpm_proto_rawDescData)
	})
	return file_outputs_rpm_proto_rawDescData
}

var file_outputs_rpm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_outputs_rpm_proto_goTypes = []any{
	(*RpmSensorOutput)(nil), // 0: protobuf_msgs.RpmSensorOutput
}
var file_outputs_rpm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outputs_rpm_proto_init() }
func file_outputs_rpm_proto_init() {
	if File_outputs_rpm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_outputs_rpm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outputs_rpm_proto_goTypes,
		DependencyIndexes: file_outputs_rpm_proto_depIdxs,
		MessageInfos:      file_outputs_rpm_proto_msgTypes,
	}.Build()
	File_outputs_rpm_proto = out.File
	file_outputs_rpm_proto_rawDesc = nil
	file_outputs_rpm_proto_goTypes = nil
	file_outputs_rpm_proto_depIdxs = nil
}
