// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: outputs/rpm.proto

package pb_outputs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpmSensorOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftRpm       float32                `protobuf:"fixed32,1,opt,name=leftRpm,proto3" json:"leftRpm,omitempty"`
	LeftAngle     float32                `protobuf:"fixed32,2,opt,name=leftAngle,proto3" json:"leftAngle,omitempty"`
	RightRpm      float32                `protobuf:"fixed32,3,opt,name=rightRpm,proto3" json:"rightRpm,omitempty"`
	RightAngle    float32                `protobuf:"fixed32,4,opt,name=rightAngle,proto3" json:"rightAngle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpmSensorOutput) Reset() {
	*x = RpmSensorOutput{}
	mi := &file_outputs_rpm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpmSensorOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpmSensorOutput) ProtoMessage() {}

func (x *RpmSensorOutput) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_rpm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpmSensorOutput.ProtoReflect.Descriptor instead.
func (*RpmSensorOutput) Descriptor() ([]byte, []int) {
	return file_outputs_rpm_proto_rawDescGZIP(), []int{0}
}

func (x *RpmSensorOutput) GetLeftRpm() float32 {
	if x != nil {
		return x.LeftRpm
	}
	return 0
}

func (x *RpmSensorOutput) GetLeftAngle() float32 {
	if x != nil {
		return x.LeftAngle
	}
	return 0
}

func (x *RpmSensorOutput) GetRightRpm() float32 {
	if x != nil {
		return x.RightRpm
	}
	return 0
}

func (x *RpmSensorOutput) GetRightAngle() float32 {
	if x != nil {
		return x.RightAngle
	}
	return 0
}

var File_outputs_rpm_proto protoreflect.FileDescriptor

const file_outputs_rpm_proto_rawDesc = "" +
	"\n" +
	"\x11outputs/rpm.proto\x12\rprotobuf_msgs\"\x85\x01\n" +
	"\x0fRpmSensorOutput\x12\x18\n" +
	"\aleftRpm\x18\x01 \x01(\x02R\aleftRpm\x12\x1c\n" +
	"\tleftAngle\x18\x02 \x01(\x02R\tleftAngle\x12\x1a\n" +
	"\brightRpm\x18\x03 \x01(\x02R\brightRpm\x12\x1e\n" +
	"\n" +
	"rightAngle\x18\x04 \x01(\x02R\n" +
	"rightAngleB\x10Z\x0ease/pb_outputsb\x06proto3"

var (
	file_outputs_rpm_proto_rawDescOnce sync.Once
	file_outputs_rpm_proto_rawDescData []byte
)

func file_outputs_rpm_proto_rawDescGZIP() []byte {
	file_outputs_rpm_proto_rawDescOnce.Do(func() {
		file_outputs_rpm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outputs_rpm_proto_rawDesc), len(file_outputs_rpm_proto_rawDesc)))
	})
	return file_outputs_rpm_proto_rawDescData
}

var file_outputs_rpm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_outputs_rpm_proto_goTypes = []any{
	(*RpmSensorOutput)(nil), // 0: protobuf_msgs.RpmSensorOutput
}
var file_outputs_rpm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_outputs_rpm_proto_init() }
func file_outputs_rpm_proto_init() {
	if File_outputs_rpm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outputs_rpm_proto_rawDesc), len(file_outputs_rpm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outputs_rpm_proto_goTypes,
		DependencyIndexes: file_outputs_rpm_proto_depIdxs,
		MessageInfos:      file_outputs_rpm_proto_msgTypes,
	}.Build()
	File_outputs_rpm_proto = out.File
	file_outputs_rpm_proto_goTypes = nil
	file_outputs_rpm_proto_depIdxs = nil
}
