// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: control/control.proto

package pb_control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tell a client if a given client/rover is connected or not
type ConnectionState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Client          string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Connected       bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	TimestampOffset int64                  `protobuf:"varint,3,opt,name=timestampOffset,proto3" json:"timestampOffset,omitempty"` // the offset between the system time of the client/rover and the server
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectionState) Reset() {
	*x = ConnectionState{}
	mi := &file_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionState) ProtoMessage() {}

func (x *ConnectionState) ProtoReflect() protoreflect.Message {
	mi := &file_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionState.ProtoReflect.Descriptor instead.
func (*ConnectionState) Descriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionState) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ConnectionState) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ConnectionState) GetTimestampOffset() int64 {
	if x != nil {
		return x.TimestampOffset
	}
	return 0
}

type ControlError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlError) Reset() {
	*x = ControlError{}
	mi := &file_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlError) ProtoMessage() {}

func (x *ControlError) ProtoReflect() protoreflect.Message {
	mi := &file_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlError.ProtoReflect.Descriptor instead.
func (*ControlError) Descriptor() ([]byte, []int) {
	return file_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlError) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_control_control_proto protoreflect.FileDescriptor

const file_control_control_proto_rawDesc = "" +
	"\n" +
	"\x15control/control.proto\x12\rprotobuf_msgs\"q\n" +
	"\x0fConnectionState\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12(\n" +
	"\x0ftimestampOffset\x18\x03 \x01(\x03R\x0ftimestampOffset\"F\n" +
	"\fControlError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestampB\x10Z\x0ease/pb_controlb\x06proto3"

var (
	file_control_control_proto_rawDescOnce sync.Once
	file_control_control_proto_rawDescData []byte
)

func file_control_control_proto_rawDescGZIP() []byte {
	file_control_control_proto_rawDescOnce.Do(func() {
		file_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_control_proto_rawDesc), len(file_control_control_proto_rawDesc)))
	})
	return file_control_control_proto_rawDescData
}

var file_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_control_control_proto_goTypes = []any{
	(*ConnectionState)(nil), // 0: protobuf_msgs.ConnectionState
	(*ControlError)(nil),    // 1: protobuf_msgs.ControlError
}
var file_control_control_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_control_proto_init() }
func file_control_control_proto_init() {
	if File_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_control_proto_rawDesc), len(file_control_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_control_proto_goTypes,
		DependencyIndexes: file_control_control_proto_depIdxs,
		MessageInfos:      file_control_control_proto_msgTypes,
	}.Build()
	File_control_control_proto = out.File
	file_control_control_proto_goTypes = nil
	file_control_control_proto_depIdxs = nil
}
