// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: segmentation/segmentation.proto

package pb_segmentation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control messages exchanged by client(s), the server and the car to send data in multiple segments
type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      int64                  `protobuf:"varint,1,opt,name=packetId,proto3" json:"packetId,omitempty"`           // unique and increasing id of each the packet that this segment is part of
	SegmentId     int64                  `protobuf:"varint,2,opt,name=segmentId,proto3" json:"segmentId,omitempty"`         // unique and increasing id of the segment within the packet
	TotalSegments int64                  `protobuf:"varint,3,opt,name=totalSegments,proto3" json:"totalSegments,omitempty"` // total number of segments in the packet
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                    // data of the segment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_segmentation_segmentation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segmentation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_segmentation_segmentation_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetPacketId() int64 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *Segment) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *Segment) GetTotalSegments() int64 {
	if x != nil {
		return x.TotalSegments
	}
	return 0
}

func (x *Segment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_segmentation_segmentation_proto protoreflect.FileDescriptor

const file_segmentation_segmentation_proto_rawDesc = "" +
	"\n" +
	"\x1fsegmentation/segmentation.proto\x12\rprotobuf_msgs\"}\n" +
	"\aSegment\x12\x1a\n" +
	"\bpacketId\x18\x01 \x01(\x03R\bpacketId\x12\x1c\n" +
	"\tsegmentId\x18\x02 \x01(\x03R\tsegmentId\x12$\n" +
	"\rtotalSegments\x18\x03 \x01(\x03R\rtotalSegments\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04dataB\x15Z\x13ase/pb_segmentationb\x06proto3"

var (
	file_segmentation_segmentation_proto_rawDescOnce sync.Once
	file_segmentation_segmentation_proto_rawDescData []byte
)

func file_segmentation_segmentation_proto_rawDescGZIP() []byte {
	file_segmentation_segmentation_proto_rawDescOnce.Do(func() {
		file_segmentation_segmentation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_segmentation_segmentation_proto_rawDesc), len(file_segmentation_segmentation_proto_rawDesc)))
	})
	return file_segmentation_segmentation_proto_rawDescData
}

var file_segmentation_segmentation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_segmentation_segmentation_proto_goTypes = []any{
	(*Segment)(nil), // 0: protobuf_msgs.Segment
}
var file_segmentation_segmentation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_segmentation_segmentation_proto_init() }
func file_segmentation_segmentation_proto_init() {
	if File_segmentation_segmentation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_segmentation_segmentation_proto_rawDesc), len(file_segmentation_segmentation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_segmentation_segmentation_proto_goTypes,
		DependencyIndexes: file_segmentation_segmentation_proto_depIdxs,
		MessageInfos:      file_segmentation_segmentation_proto_msgTypes,
	}.Build()
	File_segmentation_segmentation_proto = out.File
	file_segmentation_segmentation_proto_goTypes = nil
	file_segmentation_segmentation_proto_depIdxs = nil
}
