// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: debug/debug.proto

package pb_debug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Used to identify a service within the pipeline
type ServiceIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceIdentifier) Reset() {
	*x = ServiceIdentifier{}
	mi := &file_debug_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceIdentifier) ProtoMessage() {}

func (x *ServiceIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_debug_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceIdentifier.ProtoReflect.Descriptor instead.
func (*ServiceIdentifier) Descriptor() ([]byte, []int) {
	return file_debug_debug_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceIdentifier) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// An endpoint that is made available by a service
type ServiceEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // the identifier to select this endpoint
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // the zmq address to connect to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEndpoint) Reset() {
	*x = ServiceEndpoint{}
	mi := &file_debug_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEndpoint) ProtoMessage() {}

func (x *ServiceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_debug_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEndpoint.ProtoReflect.Descriptor instead.
func (*ServiceEndpoint) Descriptor() ([]byte, []int) {
	return file_debug_debug_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceEndpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// When the transceivers picks up a SensorOutput from a service, it will wrap it in a ServiceMessage message,
// so that the receiver can determine from which process the message originated
type DebugOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceIdentifier     `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`   // The service that sent the message
	Endpoint      *ServiceEndpoint       `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // The endpoint in this service that sent the message
	SentAt        int64                  `protobuf:"varint,4,opt,name=sentAt,proto3" json:"sentAt,omitempty"`    // Time in milliseconds since epoch when the message was sent
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugOutput) Reset() {
	*x = DebugOutput{}
	mi := &file_debug_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugOutput) ProtoMessage() {}

func (x *DebugOutput) ProtoReflect() protoreflect.Message {
	mi := &file_debug_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugOutput.ProtoReflect.Descriptor instead.
func (*DebugOutput) Descriptor() ([]byte, []int) {
	return file_debug_debug_proto_rawDescGZIP(), []int{2}
}

func (x *DebugOutput) GetService() *ServiceIdentifier {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *DebugOutput) GetEndpoint() *ServiceEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *DebugOutput) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *DebugOutput) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_debug_debug_proto protoreflect.FileDescriptor

const file_debug_debug_proto_rawDesc = "" +
	"\n" +
	"\x11debug/debug.proto\x12\rprotobuf_msgs\"9\n" +
	"\x11ServiceIdentifier\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"?\n" +
	"\x0fServiceEndpoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xb7\x01\n" +
	"\vDebugOutput\x12:\n" +
	"\aservice\x18\x01 \x01(\v2 .protobuf_msgs.ServiceIdentifierR\aservice\x12:\n" +
	"\bendpoint\x18\x02 \x01(\v2\x1e.protobuf_msgs.ServiceEndpointR\bendpoint\x12\x16\n" +
	"\x06sentAt\x18\x04 \x01(\x03R\x06sentAt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessageB\x0eZ\fase/pb_debugb\x06proto3"

var (
	file_debug_debug_proto_rawDescOnce sync.Once
	file_debug_debug_proto_rawDescData []byte
)

func file_debug_debug_proto_rawDescGZIP() []byte {
	file_debug_debug_proto_rawDescOnce.Do(func() {
		file_debug_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_debug_debug_proto_rawDesc), len(file_debug_debug_proto_rawDesc)))
	})
	return file_debug_debug_proto_rawDescData
}

var file_debug_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_debug_debug_proto_goTypes = []any{
	(*ServiceIdentifier)(nil), // 0: protobuf_msgs.ServiceIdentifier
	(*ServiceEndpoint)(nil),   // 1: protobuf_msgs.ServiceEndpoint
	(*DebugOutput)(nil),       // 2: protobuf_msgs.DebugOutput
}
var file_debug_debug_proto_depIdxs = []int32{
	0, // 0: protobuf_msgs.DebugOutput.service:type_name -> protobuf_msgs.ServiceIdentifier
	1, // 1: protobuf_msgs.DebugOutput.endpoint:type_name -> protobuf_msgs.ServiceEndpoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_debug_debug_proto_init() }
func file_debug_debug_proto_init() {
	if File_debug_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_debug_debug_proto_rawDesc), len(file_debug_debug_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_debug_debug_proto_goTypes,
		DependencyIndexes: file_debug_debug_proto_depIdxs,
		MessageInfos:      file_debug_debug_proto_msgTypes,
	}.Build()
	File_debug_debug_proto = out.File
	file_debug_debug_proto_goTypes = nil
	file_debug_debug_proto_depIdxs = nil
}
