name: generate packages

on:
  push:
    branches:
      - main

jobs:
  generate-packages:
    name: build inside devcontainer
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests in devcontainer
        uses: devcontainers/ci@v0.3
        with:    
          push: never
          runCmd: make clean; make build
      - name: Commit generated code
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # Add all changes to packages
          add: "packages/*"
          author_name: Packagebuilder Bot
          default_author: github_actions

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "build: update packages (automated)"


